version: '3'

services:
  backend:
    build: .
    image: immuni-efgs-gateway-client/client
    container_name: immuni-efgs-gateway-client
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - PROXY_HOST=
      - PROXY_PORT=
      - PROXY_USER=
      - PROXY_PWD=
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=KEYS
      - MONGODB_USER=efgs
      - MONGODB_PWD=efgs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PWD=efgs
      - SIGN_EXTERNAL_URL=https://immuni-svc-val.sogei.it/v1/pkcs7sign/efgs_bs_ita
      - SSLDP_JKS_PATH=/security/sign/sign.jks
      - SSLDP_JKS_PASSWORD=password
      - SSLDP_CERT_PASSWORD=password
      - EFGS_BASE_URL=https://acc-efgs-ws.tech.ec.europa.eu
      - SSLEFGS_JKS_PATH=/security/server/server.jks
      - SSLEFGS_JKS_PASSWORD=password
      - SSLEFGS_CERT_PASSWORD=password
      - TRUST_JKS_PATH=/security/sign/trust.jks
      - TRUST_JKS_PASSWORD=password

    networks:
      backend:
      persistence:

networks:
  persistence:
  backend:
