version: '3'

services:
  backend:
    build: .
    image: immuni-efgs-gateway-client/client
    container_name: immuni-efgs-gateway-client
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - PROXY_HOST=proxy
      - PROXY_PORT=80
      - PROXY_USER=user
      - PROXY_PWD=password
      - MONGO_DB_URI=mongodb://user:password@mongodb:27017/DB
      - REDIS_URL=redis://:password@redis:17955
      - SIGN_EXTERNAL_URL=https://immuni-svc-val.sogei.it/v1/pkcs7sign/efgs_bs_ita
      - SSLDP_JKS_PATH=/security/sslclient/sign.jks
      - SSLDP_JKS_PASSWORD=password
      - SSLDP_CERT_PASSWORD=password
      - EFGS_BASE_URL=https://acc-efgs-ws.tech.ec.europa.eu
      - SSLEFGS_JKS_PATH=/security/sslclient/server.jks
      - SSLEFGS_JKS_PASSWORD=password
      - SSLEFGS_CERT_PASSWORD=password
      - TRUST_JKS_PATH=/security/truststore/truststore.jks
      - TRUST_JKS_PASSWORD=efg_acc
    volumes:
      - c:\security\sslclient:/security/sslclient
      - c:\security\truststore:/security/truststore
      - c:\immuni-gateway-client\config:/immuni-gateway-client/config
    networks:
      backend:
      persistence:

networks:
  persistence:
  backend:
